import { EventItem } from "@/lib/types";

export const events: EventItem[] = [
  // Cultural - Music
  {
    id: "evt-music-solo-1",
    slug: "melody-master",
    title: "Melody Master",
    description: "Solo singing competition showcasing vocal talent.",
    categorySlug: "music",
    subCategorySlug: "solo",
    kind: "cultural",
    venue: "Auditorium A",
    startDate: "2025-02-10T10:00:00.000Z",
    endDate: "2025-02-10T12:00:00.000Z",
    price: 199,
    capacity: 100,
    tags: ["singing", "solo"],
    isRegistrationOpen: true,
  },
  {
    id: "evt-music-band-1",
    slug: "battle-of-bands",
    title: "Battle of the Bands",
    description: "Bands compete for the grand title.",
    categorySlug: "music",
    subCategorySlug: "band",
    kind: "cultural",
    venue: "Main Stage",
    startDate: "2025-02-11T16:00:00.000Z",
    endDate: "2025-02-11T20:00:00.000Z",
    price: 299,
    capacity: 500,
    tags: ["band", "rock"],
    isRegistrationOpen: true,
  },
  // Cultural - Dance
  {
    id: "evt-dance-solo-1",
    slug: "solo-groove",
    title: "Solo Groove",
    description: "Solo dance face-off across styles.",
    categorySlug: "dance",
    subCategorySlug: "solo",
    kind: "cultural",
    venue: "Studio 1",
    startDate: "2025-02-12T09:00:00.000Z",
    endDate: "2025-02-12T11:00:00.000Z",
    price: 149,
    capacity: 120,
    tags: ["dance", "solo"],
    isRegistrationOpen: true,
  },
  {
    id: "evt-dance-group-1",
    slug: "crew-showdown",
    title: "Crew Showdown",
    description: "Group dance crews battle it out.",
    categorySlug: "dance",
    subCategorySlug: "group",
    kind: "cultural",
    venue: "Main Stage",
    startDate: "2025-02-12T14:00:00.000Z",
    endDate: "2025-02-12T17:00:00.000Z",
    price: 249,
    capacity: 400,
    tags: ["dance", "group"],
    isRegistrationOpen: false,
  },
  // Cultural - Drama
  {
    id: "evt-drama-street-1",
    slug: "nukkad-natak",
    title: "Nukkad Natak",
    description: "Street play addressing social themes.",
    categorySlug: "drama",
    subCategorySlug: "street",
    kind: "cultural",
    venue: "Quad Lawn",
    startDate: "2025-02-13T10:00:00.000Z",
    endDate: "2025-02-13T11:30:00.000Z",
    price: 0,
    capacity: 300,
    tags: ["drama", "street"],
    isRegistrationOpen: true,
  },
  {
    id: "evt-drama-theatre-1",
    slug: "stage-saga",
    title: "Stage Saga",
    description: "Theatre performance by top teams.",
    categorySlug: "drama",
    subCategorySlug: "theatre",
    kind: "cultural",
    venue: "Auditorium B",
    startDate: "2025-02-13T18:00:00.000Z",
    endDate: "2025-02-13T20:00:00.000Z",
    price: 199,
    capacity: 350,
    tags: ["drama", "theatre"],
    isRegistrationOpen: true,
  },
  // Sports - Football
  {
    id: "evt-football-5v5-1",
    slug: "five-a-side",
    title: "Five-a-side Tournament",
    description: "Fast-paced 5v5 football tournament.",
    categorySlug: "football",
    subCategorySlug: "5v5",
    kind: "sports",
    venue: "Sports Ground 2",
    startDate: "2025-02-14T08:00:00.000Z",
    endDate: "2025-02-14T16:00:00.000Z",
    price: 499,
    capacity: 32,
    tags: ["football", "5v5"],
    isRegistrationOpen: true,
  },
  {
    id: "evt-football-11v11-1",
    slug: "league-championship",
    title: "League Championship",
    description: "Full 11v11 football matches across days.",
    categorySlug: "football",
    subCategorySlug: "11v11",
    kind: "sports",
    venue: "Main Football Ground",
    startDate: "2025-02-15T08:00:00.000Z",
    endDate: "2025-02-16T18:00:00.000Z",
    price: 999,
    capacity: 16,
    tags: ["football", "11v11"],
    isRegistrationOpen: false,
  },
  // Sports - Basketball
  {
    id: "evt-basketball-3x3-1",
    slug: "streetball-slam",
    title: "Streetball Slam",
    description: "3x3 high-intensity hoops.",
    categorySlug: "basketball",
    subCategorySlug: "3x3",
    kind: "sports",
    venue: "Court B",
    startDate: "2025-02-14T10:00:00.000Z",
    price: 399,
    capacity: 24,
    tags: ["basketball", "3x3"],
    isRegistrationOpen: true,
  },
  {
    id: "evt-basketball-5x5-1",
    slug: "court-kings",
    title: "Court Kings",
    description: "Classic 5x5 basketball showdowns.",
    categorySlug: "basketball",
    subCategorySlug: "5x5",
    kind: "sports",
    venue: "Indoor Arena",
    startDate: "2025-02-15T12:00:00.000Z",
    price: 699,
    capacity: 16,
    tags: ["basketball", "5x5"],
    isRegistrationOpen: true,
  },
  // Sports - Athletics
  {
    id: "evt-athletics-track-1",
    slug: "sprint-100m",
    title: "100m Sprint",
    description: "Track sprint for best times.",
    categorySlug: "athletics",
    subCategorySlug: "track",
    kind: "sports",
    venue: "Track 1",
    startDate: "2025-02-16T09:00:00.000Z",
    price: 99,
    capacity: 100,
    tags: ["athletics", "track"],
    isRegistrationOpen: true,
  },
  {
    id: "evt-athletics-field-1",
    slug: "long-jump",
    title: "Long Jump",
    description: "Field event testing distance.",
    categorySlug: "athletics",
    subCategorySlug: "field",
    kind: "sports",
    venue: "Field A",
    startDate: "2025-02-16T11:00:00.000Z",
    price: 99,
    capacity: 60,
    tags: ["athletics", "field"],
    isRegistrationOpen: true,
  },
];

export function getEventBySlug(slug: string): EventItem | undefined {
  return events.find((e) => e.slug === slug);
}

export function getEventsByCategorySlug(categorySlug: string) {
  return events.filter((e) => e.categorySlug === categorySlug);
}

export function getEventsByCategoryAndSubcategory(
  categorySlug: string,
  subCategorySlug?: string
) {
  return events.filter(
    (e) =>
      e.categorySlug === categorySlug &&
      (subCategorySlug ? e.subCategorySlug === subCategorySlug : true)
  );
}

