import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/env-fallback";
import ClientProviders from "@/components/ClientProviders";
import EnvWarning from "@/components/EnvWarning";
import { Toaster } from "sonner";
import NavProgress from "@/components/NavProgress";
import Navbar from "@/components/Nav";
import Link from "next/link"; 
import PageTransitionClient from "@/components/PageTransitionClient";
import PaymentReturnSync from "@/components/payments/PaymentReturnSync";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "FALAK 2025",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link
          rel="preload"
          href="/fonts/brasty-vintage.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen h-full flex flex-col overflow-x-hidden`}>
        <ClientProviders>
          <PaymentReturnSync />
          <EnvWarning />

          {/* Navbar */}
      <Navbar />

          {/* Fixed Logo */}
<div
  className={`fixed -top-6 right-0 z-[9999] xl:left-4 xl:top-[-3.5rem] xl:right-auto transition-all duration-300 opacity-100`}
  style={{ transform: "translateZ(0)" }}
>
  <Link href="/" aria-label="Go to homepage">
    <Image
      src="/images/logo.png"
      alt="Falak Logo"
      width={400}
      height={320}
      className="w-[200px] h-[120px] xl:w-[300px] xl:h-[200px] cursor-pointer"
      priority
    />
  </Link>
</div>


          <main className="flex-1 w-full min-h-screen">
            <PageTransitionClient>{children}</PageTransitionClient>
          </main>
          <NavProgress />
          <Toaster richColors position="bottom-right" />
        </ClientProviders>
      </body>
    </html>
  );
}
